### ISSUE TITLE
BE - Pokeapi API Controller

### ISSUE THREAD

**Issue by binnssss** [CUPA-mario/pokemon-diary#4]
We need an API Controller to access the data to access the data provided by the [Pokeapi
](https://pokeapi.co/)
There's an existing [drupal module for Pokeapi](https://www.drupal.org/search/site/pokeapi), but not implemented on current recommended Drupal version.

Possible approach may be to ~ **create our own custom module** ~ or ~ **update the current one as an opportunity to contribute on Drupal community** ~

**Comment by papaaldrin** [comment]
Created a pokeapi module that can be used on this project that is included in https://github.com/CUPA-mario/pokemon-diary/issues/10.

**Comment by binnssss** [comment]
Submitted a Pull Request

**Comment by binnssss** [comment]
Moved Controller functions to Services
