### ISSUE TITLE
[BE] - Auto assign trainer role to user registered via registration link

### ISSUE THREAD

**Issue by binnssss** [CUPA-mario/pokemon-diary#56]

**Comment by hahaharisoman** [comment]
References:

- https://www.drupal.org/forum/support/post-installation/2023-03-17/assign-role-to-user-at-user-registration
- https://www.drupal.org/project/registration_role

Commands run:

- ddev composer require 'drupal/registration_role:^2.0'
- ddev drush en registration_role
- ddev drush cr

How to Configure:

1.  Go to: /admin/people/registration-role
2.  Select role for new registered users:
![Image](https://github.com/CUPA-mario/pokemon-diary/assets/63938675/852b83ea-92c4-4e2a-b77c-b59a368defd3)
then click Save configration.
3. Register a new user.
4. Check in User list if newly created account is assigned to your specific role: https://pokemon-diary.ddev.site/admin/people
![Image](https://github.com/CUPA-mario/pokemon-diary/assets/63938675/f53613b6-4333-410b-8155-ac024118a600)
